# application.yml 示例
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://74.48.15.22:3306/nova_forum?serverTimezone=Asia/Shanghai
    username: root # 你的数据库用户名
    password: mysql_jRkQGS # 你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: 74.48.15.22
      database: 0